### PR TITLE
Add type mapping annotation and fix createIndex() method failure

### LINKED ISSUE #24: Need a way to add a timestamp as a date field to the payload in elasticsearch
**Description:**
Need a way to add a timestamp as a date field to the payload in elasticsearch

**Affected Product Version:**
siddhi-store-elasticsearch v2.0.0

**OS, DB, other environment details and versions:**    
APIM Analytics v2.6.0
elasticsearch v7.1.1

### PR DESCRIPTION
**Pull request by dilini-muthumala**
## Purpose
This fixes following two issues:
1. https://github.com/siddhi-io/siddhi-store-elasticsearch/issues/22
2. https://github.com/siddhi-io/siddhi-store-elasticsearch/issues/24

In addition to this,
error log is printed (instead of debug log) when an `ElasticsearchStatusException` is thrown from `createIndex()` method in `ElasticsearchEventTable` class so that the user will get to know when index creation fails. 

### Fix for #22 :
Removing `builder.startObject(indexType);` and its corresponding `builder.endObject();` from the `createIndex()` method in `ElasticsearchEventTable` class. 

### Improvement proposed to fix #24 :
Coming up with new annotation `TypeMappings`. Please refer example config below:
```
@Store(type="elasticsearch", @TypeMappings(requestTimestamp="date", latitude="geo_point", longitude="geo_point"), elasticsearch.member.list="http://localhost:9200",username="elastic", password="changeme", bulk.actions="10000", bulk.size="5")
define table ESTable (meta_clientType string, requestTimestamp long, latitude double, longitude double);
```
Here we can specify the list of type mappings. 
In this example config, 'requestTimestamp' attribute is mapped to type 'date', 'latitude' attribute is being mapped to type 'geo_point' and so on. 

## Release note
Introduce `TypeMappings` annotation.

## Documentation
TODO

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Migrations (if applicable)
TODO

## Test environment
- APIM Analytics v2.6.0
- elasticsearch v7.1.1

### CODE REVIEW

File: component/src/main/java/org/wso2/extension/siddhi/store/elasticsearch/ElasticsearchEventTable.java [hunk 1]
```diff
@@ -845,43 +856,41 @@ private void createIndex() {
             XContentBuilder builder = XContentFactory.jsonBuilder();
             builder.startObject();
             {
-                builder.startObject(indexType);
```
Comment (ramindu90) [inline component/src/main/java/org/wso2/extension/siddhi/store/elasticsearch/ElasticsearchEventTable.java]: @dilini-muthumala , shall change the logic a bit and keep indexType? 
If user gives a value for indexType we'll have builder.startObject(indexType); if it's not we'll go for this PRs approach.

File: component/src/main/java/org/wso2/extension/siddhi/store/elasticsearch/ElasticsearchEventTable.java [hunk 2]
```diff
@@ -901,8 +910,21 @@ private void createIndex() {
             throw new ElasticsearchEventTableException("Error while creating indices for table id : '" +
                     tableDefinition.getId(), e);
         } catch (ElasticsearchStatusException e) {
-            logger.debug("Elasticsearch status exception occurs while creating index for table id: " +
+            logger.error("Elasticsearch status exception occurs while creating index for table id: " +
```
Comment (ramindu90) [inline component/src/main/java/org/wso2/extension/siddhi/store/elasticsearch/ElasticsearchEventTable.java]: Shall we fix the "occurs" typo as well? (Elasticsearch status exception occurred while...)

Comment (dilini-muthumala) [reply component/src/main/java/org/wso2/extension/siddhi/store/elasticsearch/ElasticsearchEventTable.java]: Fixed in  0522934

File: component/src/main/java/org/wso2/extension/siddhi/store/elasticsearch/ElasticsearchEventTable.java (hunk 1 above)
Comment (dilini-muthumala) [reply component/src/main/java/org/wso2/extension/siddhi/store/elasticsearch/ElasticsearchEventTable.java]: +1. Added in 0522934
