### PR TITLE
Give support to siddhi-store-elasticsearch to add custom JSON documents into elasticsearch indexes

### LINKED ISSUE #31: Write data in the root field "_source" of document in elasticsearch
**Description:**
Elasticsearch module 3.0.0 doesn't write data to the root of document (in field _source).

**Suggested Labels:**
siddhi,elasticsearch

**Suggested Assignees:**
@suhothayan 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
```
@source(type = 'http', receiver.url = "http://0.0.0.0:8006/nlins",@map(type = 'json',@attributes(json='$.event')))
define stream NlinsStream (json string);

@store(type='elasticsearch',hostname='localhost',port='9200',index.name='siddhi')
define table Elastic (event1 string);

partition with (json:getString(json,"computer_name") of NlinsStream)
begin
    from every e1=NlinsStream[RULE#1], e2=NlinsStream[RULE#2], e3=NlinsStream[RULE3]
    select json:toString(json:setElement(e1.json,'$',"updated",'new_field')) as event1
    insert into Elastic;
end;
```
The result is:
```
{
        "_index" : "siddhi",
        "_type" : "_doc",
        "_id" : "KRwl3mwBgY4BQ9S8DCa9",
        "_score" : 1.0,
        "_source" : {
          "event1" : """{MY_JSON_DATA}""",
        }
}
```
Expected:
```
{
        "_index" : "siddhi",
        "_type" : "_doc",
        "_id" : "KRwl3mwBgY4BQ9S8DCa9",
        "_score" : 1.0,
        "_source" : {
          {MY_JSON_DATA},
        }
}
```

### PR DESCRIPTION
**Pull request by sahandilshan**
## User Stories
 You can use the sink as follow,
``` 
@sink(type='elasticsearch', host='172.17.0.2', port='9200',
                        index.name='stock_index',
                        @map(type='json', @payload(""" {
                        "StockData":{
                            "Symbol":"{{symbol}}",
                            "Price":{{price}},
                            "Volume":{{volume}}
                            }
                        } """)))
                        define stream stock_stream(symbol string, price float, volume long);
```

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java [hunk 1]
```diff
@@ -0,0 +1,287 @@
...
+                elasticsearchConfigs.getIndexName());
+        try {
+            JsonElement parse = new JsonParser().parse((String) payload);
+            if (parse.isJsonArray()) {
+                JsonArray jsonArray = parse.getAsJsonArray();
+                for (JsonElement jsonElement : jsonArray) {
+                    siddhiIndexRequest.source(jsonElement.toString(), XContentType.JSON);
+                    elasticsearchConfigs.getBulkProcessor().add(siddhiIndexRequest);
+                }
+                logger.debug(payload + " has been successfully added.");
```
Comment (mohanvive) [inline component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java]: improve this with isDebugEnabled flag

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java [hunk 2]
```diff
@@ -0,0 +1,287 @@
...
+            } else if (parse.isJsonObject()) {
+                siddhiIndexRequest.source(parse.getAsJsonObject().toString(), XContentType.JSON);
+                elasticsearchConfigs.getBulkProcessor().add(siddhiIndexRequest);
+            }
```
Comment (mohanvive) [inline component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java]: Whether it could have other than json object or json array ?

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java [hunk 3]
```diff
@@ -0,0 +1,287 @@
...
+            createIndex(elasticsearchConfigs.getDefinitionId());
+        }
+    }
+
+    @Override
+    public void disconnect() {
+        try {
+            elasticsearchConfigs.getRestHighLevelClient().close();
+        } catch (IOException e) {
+            throw new ElasticsearchEventSinkException("Error while closing the connection.", e);
```
Comment (mohanvive) [inline component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java]: Give more context to the error message.

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java [hunk 4]
```diff
@@ -0,0 +1,287 @@
...
+                        .put(SETTING_INDEX_NUMBER_OF_REPLICAS, elasticsearchConfigs.getNumberOfReplicas()));
+        if (elasticsearchConfigs.getIndexAlias() != null) {
+            request.alias(new Alias(elasticsearchConfigs.getIndexAlias()));
+        }
+        try {
+            elasticsearchConfigs.getRestHighLevelClient().indices().create(request, RequestOptions.DEFAULT);
+            logger.debug("A sink id: " + definitionId + " is created with the provided information.");
+        } catch (IOException e) {
+            throw new ElasticsearchEventSinkException("Error while creating indices for sink id : '" +
+                    definitionId, e);
```
Comment (mohanvive) [inline component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java]: Isn't using definitionID for sinkID wrong ?

Comment (mohanvive) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java]: Check below log as well.

File: pom.xml [hunk 5]
```diff
@@ -56,6 +57,11 @@
                 <artifactId>siddhi-annotations</artifactId>
                 <version>${siddhi.version}</version>
             </dependency>
+            <dependency>
+                <groupId>io.siddhi.extension.map.json</groupId>
+                <artifactId>siddhi-map-json</artifactId>
+                <version>${siddhi.map.json.version}</version>
+            </dependency>
```
Comment (mohanvive) [inline pom.xml]: You need above extension only for tests right? Then add `Test` scope for it.

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java (hunk 2 above)
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java]: When I test the elasticsearch sink with the editor, I got the json string as json object, but when I run the test case in the project I got the json string as json array. That's why added support for both the json object and the json array.

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchEventTable.java [hunk 6]
```diff
@@ -366,9 +234,12 @@
      */
     @Override
     protected void init(TableDefinition tableDefinition, ConfigReader configReader) {
-        this.attributes = tableDefinition.getAttributeList();
-        Annotation storeAnnotation = AnnotationHelper.getAnnotation(SiddhiConstants.ANNOTATION_STORE, tableDefinition
-                .getAnnotations());
+
+        ElasticsearchConfigs.setLogger(logger);
```
[the remark this answers is not in the document]
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchEventTable.java]: Fixed in `Create a logger for ElasticSearchConfigs class` commit

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchEventTable.java [hunk 7]
```diff
@@ -989,11 +594,11 @@ private void createIndex() {
...
         }
-        if (indexAlias != null) {
-            request.alias(new Alias(indexAlias));
+        if (elasticsearchConfigs.getIndexAlias() != null) {
+            request.alias(new Alias(elasticsearchConfigs.getIndexAlias()));
         }
         try {
-            restHighLevelClient.indices().create(request, RequestOptions.DEFAULT);
+            elasticsearchConfigs.getRestHighLevelClient().indices().create(request, RequestOptions.DEFAULT);
             logger.debug("A table id: " + tableDefinition.getId() + " is created with the provided information.");
```
[the remark this answers is not in the document]
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchEventTable.java]: Fixed in `https://github.com/siddhi-io/siddhi-store-elasticsearch/pull/41/commits/924dd015385650bb21d22d5c5386cec96b27f00c` commit

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java (hunk 1 above)
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java]: Fixed in 924dd01 commit

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java (hunk 4 above)
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java]: Fixed in https://github.com/siddhi-io/siddhi-store-elasticsearch/pull/41/commits/8887cc35f24420f2482087ac0c3b1e1aea2e6ccf commit

File: pom.xml (hunk 5 above)
Comment (sahandilshan) [reply pom.xml]: Fixed in https://github.com/siddhi-io/siddhi-store-elasticsearch/pull/41/commits/d19e2e20f87be7d4a4772619796a5dfbc40bd36b commit

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java (hunk 3 above)
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/sink/ElasticsearchSink.java]: Fixed in https://github.com/siddhi-io/siddhi-store-elasticsearch/pull/41/commits/8887cc35f24420f2482087ac0c3b1e1aea2e6ccf commit

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java [hunk 8]
```diff
@@ -0,0 +1,532 @@
...
+    private String listOfHostnames;
+    private String definitionId;
+    private Annotation storeAnnotation;
+    private ElasticsearchSink elasticsearchSink;
+
+    public ElasticsearchConfigs() { // calls from ElasticSearchEventTable
+
+    }
+
+    public ElasticsearchConfigs(ElasticsearchSink elasticsearchSink) { // calls from ElasticSearchSink
```
Comment (mohanvive) [inline component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: Do we need both constructor and init method ?

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java [hunk 9]
```diff
@@ -0,0 +1,532 @@
...
+                trustStoreType = storeAnnotation.getElement(ANNOTATION_ELEMENT_TRUSRTSTORE_TYPE);
+            } else {
+                trustStoreType = configReader.readConfig(ANNOTATION_ELEMENT_TRUSRTSTORE_TYPE, trustStoreType);
+            }
+            if (!ElasticsearchTableUtils.isEmpty(storeAnnotation.getElement(ANNOTATION_ELEMENT_MEMBER_LIST))) {
+                listOfHostnames = storeAnnotation.getElement(ANNOTATION_ELEMENT_MEMBER_LIST);
+            }
+        } else {
+            throw new SiddhiAppCreationException("Elasticsearch Store annotation list null for " + type +
+                    " id : '" + definition.getId() + "', required properties cannot be resolved.");
```
Comment (mohanvive) [inline component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: Improve the error message bit more.

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java [hunk 10]
```diff
@@ -0,0 +1,532 @@
...
+        if (listOfHostnames != null) {
+            String[] hostNameList = listOfHostnames.split(",");
+            httpHostList = new HttpHost[hostNameList.length];
+            for (int i = 0; i < httpHostList.length; i++) {
+                try {
+                    URL domain = new URL(hostNameList[i]);
+                    httpHostList[i] = new HttpHost(domain.getHost(), domain.getPort(), domain.getProtocol());
+                } catch (MalformedURLException e) {
+                    throw new SiddhiAppCreationException("Provided elastic search hostname url list is " +
+                            "malformed of " + type + " id : '" + definition.getId() + ".", e);
```
Comment (mohanvive) [inline component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: Add the url list to the error message.

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java [hunk 11]
```diff
@@ -0,0 +1,532 @@
...
+
+            int numberOfActions = request.numberOfActions();
+            if (logger.isDebugEnabled()) {
+                logger.debug("Executing bulk [{" + executionId + "}] with {" + numberOfActions + "} requests");
+            }
+        }
+
+        @Override
+        public void afterBulk(long executionId, BulkRequest request, BulkResponse response) {
+
```
Comment (mohanvive) [inline component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: Don't have spaces between the method content and method definition.

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java [hunk 12]
```diff
@@ -0,0 +1,532 @@
...
+                                    + " message : " + itemResponse.getResponse().toString());
+                        }
+                    }
+                }
+            } else {
+                if (logger.isDebugEnabled()) {
+                    logger.debug("Bulk [{" + executionId + "}] completed in {" + response.getTook().getMillis() +
+                            "} milliseconds");
+                    for (BulkItemResponse itemResponse : response) {
+                        logger.trace("Bulk [{" + executionId + "}] completed for : " +
```
Comment (mohanvive) [inline component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: Whether log trace works within debug log enabled condition?

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java [hunk 13]
```diff
@@ -0,0 +1,532 @@
...
+            if (request.requests().size() > 0) {
+                if (failure instanceof Exception && request.requests().get(0) instanceof SiddhiIndexRequest) {
+                    for (DocWriteRequest docWriteRequest : request.requests()) {
+                        SiddhiIndexRequest siddhiIndexRequest = (SiddhiIndexRequest) docWriteRequest;
+                        elasticsearchSink.onError(siddhiIndexRequest.getPayload(), siddhiIndexRequest
+                                .getDynamicOptions(), (Exception) failure);
+                    }
+                }
+            }
+            logger.error("Failed to execute bulk", failure);
```
Comment (mohanvive) [inline component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: Improve the error message.

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java (hunk 12 above)
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: yes

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java (hunk 13 above)
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: Fixed in https://github.com/siddhi-io/siddhi-store-elasticsearch/pull/41/commits/2c90b5856b203a9ad479c745f00b96442646fa04

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java (hunk 11 above)
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: Fixed in https://github.com/siddhi-io/siddhi-store-elasticsearch/pull/41/commits/2c90b5856b203a9ad479c745f00b96442646fa04

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java (hunk 10 above)
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: Fixed in https://github.com/siddhi-io/siddhi-store-elasticsearch/pull/41/commits/2c90b5856b203a9ad479c745f00b96442646fa04

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java (hunk 9 above)
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: Fixed in https://github.com/siddhi-io/siddhi-store-elasticsearch/pull/41/commits/2c90b5856b203a9ad479c745f00b96442646fa04

File: component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java (hunk 8 above)
Comment (sahandilshan) [reply component/src/main/java/io/siddhi/extension/store/elasticsearch/ElasticsearchConfigs.java]: Yes, there are two constructors in the ElasticsearchConfig, so it's better to have both init and constructor separately.
